spring:
  application:
    name: 02_SBSS_Spring_Security_JDBC_Auth_app

    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sb_springsecurity
    username: root
    password: test
  jpa:
    show-sql: true
    
    